spring:
  application:
    name: java-producers

  rabbitmq:
    host: localhost
    port: 5672
    username: illustre
    password: ithQW12ink!@

producer:
  crm:
    base-url: http://localhost:8393
  inventory:
    base-url: http://localhost:8393
